file=open("output.txt",'w')
wrt=str(input("Enter text to write in the file: "))
writing_file=file.write(wrt+"\n")
print("Data successfully written to output.txt")
file.close()
file1=open("output.txt",'a')
appn=str(input("Enter additional text to append: "))
append_file=file1.write(appn+'\n')
print("Data successfully appended")
file1.close()
file2=open("output.txt",'r')
read_file=file2.read()
print(read_file)

file2.close()